resources:
- name: main
  type: git
  source:
    uri: https://github.com/ShivamD1310/scrap-and-dump.git
    branch: main  # Replace with your branch name if different

jobs:
- name: fetch-credentials-and-login
  plan:
  - get: main  
    trigger: true
  - task: retrieve-secrets
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/vault
      outputs:
        - name: credential 
      run:
        path: sh
        args:
        - -c
        - |
          export VAULT_ADDR='http://127.0.0.1:8200'
          export VAULT_TOKEN='root
          
          vault login $VAULT_TOKEN
          # Create directory for storing credentials
          mkdir -p credential
          
          # Define the path to the secrets in Vault
          SECRET_PATH="secret/task6"  

          echo "Retrieving secrets from path: $SECRET_PATH"

          # Retrieve secrets from Vault
          username=$(vault kv get -field=username $SECRET_PATH)
          password=$(vault kv get -field=password $SECRET_PATH)

          # Print retrieved secrets
          echo "Retrieved Username: $username"
          echo "Retrieved Password: $password"

          # Write secrets to file
          echo "export USERNAME=$username" > credential/secrets.sh
          echo "export PASSWORD=$password" >> credential/secrets.sh
          chmod +x credential/secrets.sh

          echo "Secrets have been written to credential/secrets.sh"
 # Declare this as output directory

  - task: run-login
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.9
      inputs:
      - name: credential  # Use the output of the previous task
      - name: my-repo  # Make sure to include the repository as input
      run:
        path: sh
        args:
        - -c
        - |
            
             echo "Contents of credential/secrets.sh:"
             cat credential/secrets.sh         
          # Ensure the credentials are sourced
             credential/secrets.sh
          
          # Verify that the variables are set
          echo "USERNAME: $USERNAME"
          echo "PASSWORD: $PASSWORD"
          
          # Run the Python login script from the repository
          python3 my-repo/login.py
