resources:
- name: main
  type: git
  source:
    uri: https://github.com/ShivamD1310/scrap-and-dump.git
    branch: main  # Replace with your branch name if different

jobs:
- name: fetch-credentials-and-login
  plan:
  - get: main  
    trigger: true
  
  - task: retrieve-secrets
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/vault
      outputs:
        - name: credential  # Declare this as output directory
      run:
        path: sh
        args:
        - -c
        - |
          # Set Vault address and token
          export VAULT_ADDR='http://192.168.3.117:8200'
          export VAULT_TOKEN='root'
          
          # Log in to Vault
          vault login $VAULT_TOKEN

          # Create directory for storing credentials
          mkdir -p credential
          
          # Define the path to the secrets in Vault
          SECRET_PATH="secret/task6"  

          echo "Retrieving secrets from path: $SECRET_PATH"

          # Retrieve secrets from Vault
          username=$(vault kv get -field=username $SECRET_PATH)
          password=$(vault kv get -field=password $SECRET_PATH)

          # Print retrieved secrets for debugging
          echo "Retrieved Username: $username"
          echo "Retrieved Password: $password"

          # Write secrets to file
          echo "export USERNAME=$username" > credential/secrets.sh
          echo "export PASSWORD=$password" >> credential/secrets.sh
          
          # Make sure the secrets.sh file is executable
          chmod +x credential/secrets.sh

          echo "Secrets have been written to credential/secrets.sh"

  - task: run-login
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.9
      inputs:
      - name: credential  # Use the output of the previous task
      - name: main  # Make sure to include the repository as input
      run:
        path: bash
        args:
        - -c
        - |
          # Print contents of secrets.sh for debugging
          #echo "Contents of credential/secrets.sh:"
          #cat credential/secrets.sh

          # Ensure the credentials are sourced
          set -a
          source credential/secrets.sh
          set +a

          # Verify that the variables are set
          #echo "USERNAME: $USERNAME"
          #echo "PASSWORD: $PASSWORD"
          #pip install selenium
          pip install beautifulsoup4
          pip install requests
          pip install pandas
          #pip install mechanize
          # Run the Python login script from the repository
          python3 main/login.py
